name: Publish Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: test 
        run: |
          npm i 
          npm test
      - name: Publish to npm
        if: success() && github.event_name == 'push'
        run: npm publish
        env:
          NODE_AUTH: ${{ secrets.NODE_AUTH }}