name: Publish Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org

      - name: Install Dependencies and Run Tests
        run: |
          npm install
          npm test
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH }}
          GITHUB_TOKE : ${{secrets.GITHUB_TOKEN}}
