name: Publish Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: test 
        run: |
          npm i 
          npm test
      - name: Push changes to organization repository
        run: |
          git remote add organization https://github.com/VfyJS/VfyJS.git
          git push organization HEAD:main
  
      - name: Push changes to personal repository
        run: |
          git push origin HEAD:main