name: VfyJS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  packages: read
  pull-requests: write

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@m-mdy-m'
      - name: Create GitHub issue on success
        if: success()
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.NPM_AUTH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d '{"title":"Test issue","body":"This is a test issue created using GITHUB_TOKEN"}'
