name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Login to GitHub Packages Registry
        run: npm login --registry=https://npm.pkg.github.com/ --scope=@m-mdy-m --always-auth
        env:
          NODE_AUTH_TOKEN: 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

      - name: Publish to GitHub Packages Registry
        run: npm publish --access public
